In [4]:
import numpy as np

In [7]:
#ques1
a=np.matrix([[1,2],[5,6]])
b=np.matrix([[7,4],[9,10]])
a+b

matrix([[ 8,  6],
        [14, 16]])

In [8]:
#ques2
a=np.matrix([[1,2],[5,6]])
b=np.matrix([[7,4],[9,10]])
a*b

matrix([[25, 24],
        [89, 80]])

In [9]:
#ques3
a=np.matrix([[1,2],[5,6]])
np.matrix.transpose(a)


matrix([[1, 5],
        [2, 6]])

In [10]:
#ques 4
import numpy as np
arr = np.array(['banana', 'cherry', 'apple',"guava","pickle","aeroplane"])
print(np.sort(arr))

['aeroplane' 'apple' 'banana' 'cherry' 'guava' 'pickle']


In [11]:
#ques5
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
inp_str = input("Enter a string: ")
no_punc = ""
for char in inp_str:
    if char not in punctuations:
        no_punc = no_punc + char
print("Punctuation Free String: ",no_punc)

Enter a string: isbnskqnfk39hf2>.pqfjp./?JACOIJQP
Punctuation Free String:  isbnskqnfk39hf2pqfjpJACOIJQP
